### ISSUE TITLE
./launch_gym_server.py not working

### ISSUE THREAD

**Issue by ebasatemesgen** [Omegastick/pytorch-cpp-rl#20]
**I did managed to build the code.. the issue is that I couldn't run the gym server. I keep getting this error.** 

Latitude-E50:~/eba/pytorch-cpp-rl$ ./launch_gym_server.py 
Traceback (most recent call last):
  File "./launch_gym_server.py", line 7, in <module>
    from gym_server.server import Server
  File "/home/meron/eba/sniper/test/pytorch-cpp-rl/gym_server/server.py", line 24
    def __init__(self, zmq_client: ZmqClient):
                                 ^
SyntaxError: invalid syntax

**So does with python3** 

Latitude-E50:~/eba/pytorch-cpp-rl$ python3 launch_gym_server.py 
Traceback (most recent call last):
  File "launch_gym_server.py", line 7, in <module>
    from gym_server.server import Server
  File "/home/meron/eba/sniper/test/pytorch-cpp-rl/gym_server/server.py", line 10, in <module>
    from gym_server.messages import (InfoMessage, MakeMessage, ResetMessage,
  File "/home/meron/eba/sniper/test/pytorch-cpp-rl/gym_server/messages.py", line 6, in <module>
    import msgpack
ModuleNotFoundError: No module named 'msgpack'

**Comment by Omegastick** [comment]
Looks like you don't have msgpack installed in your Python 3 environment.

**Comment by JesperLindberg** [comment]
`pip3 install msgpack` should hopefully solve this indeed.
